# Generated by Django 5.0.2 on 2026-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_vendingmachine_machinename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestock',
            name='vending_machine_slot',
            field=models.CharField(default='A1', max_length=4),
            preserve_default=False,
        ),
    ]
