# Generated by Django 5.0.2 on 2026-03-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='status',
            field=models.CharField(choices=[('active', 'Online'), ('inactive', 'Offline'), ('maintenance', 'Under Repair')], default='active', max_length=20),
        ),
    ]
