# Generated by Django 5.0.2 on 2026-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vendingmachine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='active', max_length=20),
        ),
    ]
