# Generated by Django 5.0.2 on 2026-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('closed', 'closed'), ('open', 'open')], default='closed', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='status',
            field=models.CharField(choices=[('active', 'Online'), ('inactive', 'Offline'), ('maintenance', 'Under Repair')], default='inactive', max_length=20),
        ),
    ]
