# Generated by Django 5.0.2 on 2026-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_store_closing_time_store_open_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='closed', max_length=20),
        ),
    ]
