# Generated by Django 5.0.2 on 2026-03-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='closed', max_length=20),
        ),
    ]
