# Generated by Django 5.0.2 on 2026-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_storage_alter_store_status_storagestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
