# Generated by Django 5.0.2 on 2026-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='slot_cap',
            field=models.IntegerField(default=15),
        ),
    ]
