# Generated by Django 5.0.2 on 2026-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestock',
            name='expected_demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Closed', max_length=20),
        ),
    ]
