# Generated by Django 5.0.2 on 2026-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_machinestock_expected_demand_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestock',
            name='demadn_setting',
            field=models.CharField(choices=[('auto', 'Auto'), ('set', 'Set')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='machinestock',
            name='restock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinestock',
            name='expected_demand',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='Closed', max_length=20),
        ),
    ]
