# Generated by Django 5.0.2 on 2026-03-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_machinestock_demadn_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slot',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Closed', max_length=20),
        ),
    ]
