# Generated by Django 5.0.2 on 2026-03-30 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_orderitem_slot_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestock',
            name='sold_this_month',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='Closed', max_length=20),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('store', 'Store'), ('machine', 'Machine')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval_type', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=20)),
                ('created_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.vendingmachine')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.store')),
            ],
            options={
                'unique_together': {('machine', 'interval_type', 'created_at')},
            },
        ),
    ]
