# Generated by Django 5.0.2 on 2026-03-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_machinestock_sold_this_month_alter_store_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='rain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='temperature_weather',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='weather_type',
            field=models.CharField(blank=True, choices=[('cloudy', 'cloudy'), ('sunny', 'sunny'), ('windy', 'windy'), ('stormy', 'stormy'), ('partly_cloudy', 'partly_cloudy'), ('rainy', 'rainy'), ('snowy', 'snowy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Closed', max_length=20),
        ),
    ]
