# Generated by Django 5.0.2 on 2026-04-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_sales_rain_sales_temperature_weather_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='temperature_weather',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='weather_type',
        ),
        migrations.CreateModel(
            name='Item_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('store', 'Store'), ('machine', 'Machine')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval_type', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=20)),
                ('created_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('temperature_weather', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weather_type', models.CharField(blank=True, choices=[('cloudy', 'cloudy'), ('sunny', 'sunny'), ('windy', 'windy'), ('stormy', 'stormy'), ('partly_cloudy', 'partly_cloudy'), ('rainy', 'rainy'), ('snowy', 'snowy')], max_length=20, null=True)),
                ('machine_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_sales', to='inventory.machinestock')),
                ('store_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_sales', to='inventory.storagestock')),
            ],
        ),
    ]
