# Generated by Django 5.0.2 on 2026-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_sales_rain_remove_sales_temperature_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
    ]
