# Generated by Django 5.0.2 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_order_auto_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_accept',
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open')], default='Closed', max_length=20),
        ),
    ]
