# Generated by Django 5.0.2 on 2026-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_order_auto_accept_alter_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinestock',
            name='restock_set',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
