# Generated by Django 5.0.2 on 2026-06-26 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_userprofile_role_userprofile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storage',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_storage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storage',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_storage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_vendingMachine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_vendingMachine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Closed', max_length=20),
        ),
    ]
